"""Immutable contracts for the ``swing-ranking-v1`` discovery study."""

from sts.swing_ranking.candidates import (
    ConditionSpec,
    FeatureSpec,
    StrategyProgram,
    build_feature_matrix,
    generate_candidates,
)
from sts.swing_ranking.contracts import (
    Candidate,
    CandidateGrammar,
    Charter,
    ContractViolation,
    DiscoveryProtocol,
    EntryGeometry,
    GeometryProgram,
    SignalFact,
    SourceFact,
    SourceLimitation,
    StrategyRevision,
    locked_tie_break,
    swing_ranking_charter,
)
from sts.swing_ranking.simulator import (
    DailyBar,
    EquityRecord,
    EventRecord,
    OrderRecord,
    SimulationResult,
    SimulationViolation,
    TradeRecord,
    simulate,
)

__all__ = [
    "Candidate",
    "CandidateGrammar",
    "Charter",
    "ConditionSpec",
    "ContractViolation",
    "DailyBar",
    "DiscoveryProtocol",
    "EntryGeometry",
    "EquityRecord",
    "EventRecord",
    "FeatureSpec",
    "GeometryProgram",
    "OrderRecord",
    "SignalFact",
    "SimulationResult",
    "SimulationViolation",
    "SourceFact",
    "SourceLimitation",
    "StrategyProgram",
    "StrategyRevision",
    "TradeRecord",
    "build_feature_matrix",
    "generate_candidates",
    "locked_tie_break",
    "simulate",
    "swing_ranking_charter",
]
