"""Immutable contracts for the ``swing-ranking-v1`` discovery study."""

from sts.swing_ranking.candidates import (
    ConditionSpec,
    FeatureSpec,
    ScheduledEarnings,
    StrategyProgram,
    build_feature_matrix,
    generate_candidates,
)
from sts.swing_ranking.contracts import (
    Candidate,
    CandidateGrammar,
    Charter,
    ContractViolation,
    DiscoveryProtocol,
    EntryGeometry,
    EvaluationSplit,
    GeometryProgram,
    SignalFact,
    SourceFact,
    SourceLimitation,
    SplitWindow,
    StrategyRevision,
    locked_tie_break,
    swing_ranking_charter,
)
from sts.swing_ranking.geometry import GeometrySpec, PriceFormula, resolve_geometry
from sts.swing_ranking.metrics import StrategyMetrics, calculate_metrics
from sts.swing_ranking.ranking import RankingReport, rank_strategies
from sts.swing_ranking.simulator import (
    DailyBar,
    EquityRecord,
    EventRecord,
    OrderRecord,
    SimulationResult,
    SimulationViolation,
    TradeRecord,
    simulate,
)
from sts.swing_ranking.split import derive_evaluation_split, evaluation_split_document

__all__ = [
    "Candidate",
    "CandidateGrammar",
    "Charter",
    "ConditionSpec",
    "ContractViolation",
    "DailyBar",
    "DiscoveryProtocol",
    "EntryGeometry",
    "EquityRecord",
    "EvaluationSplit",
    "EventRecord",
    "FeatureSpec",
    "GeometryProgram",
    "GeometrySpec",
    "OrderRecord",
    "PriceFormula",
    "RankingReport",
    "ScheduledEarnings",
    "SignalFact",
    "SimulationResult",
    "SimulationViolation",
    "SourceFact",
    "SourceLimitation",
    "SplitWindow",
    "StrategyMetrics",
    "StrategyProgram",
    "StrategyRevision",
    "TradeRecord",
    "build_feature_matrix",
    "calculate_metrics",
    "derive_evaluation_split",
    "evaluation_split_document",
    "generate_candidates",
    "locked_tie_break",
    "rank_strategies",
    "resolve_geometry",
    "simulate",
    "swing_ranking_charter",
]
